# Generated by Django 4.2.7 on 2025-08-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tema para organização das proposições (ex: Educação, Segurança Pública)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do tema')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do tema')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo da proposição (ex: PL, PEC, MPV)', max_length=10)),
                ('numero', models.IntegerField(help_text='Número da proposição')),
                ('ano', models.IntegerField(help_text='Ano da proposição')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da proposição no sistema')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização da proposição')),
                ('tema', models.ForeignKey(help_text='Tema ao qual esta proposição pertence', on_delete=django.db.models.deletion.CASCADE, related_name='proposicoes', to='pauta.tema')),
            ],
            options={
                'verbose_name': 'Proposição',
                'verbose_name_plural': 'Proposições',
                'ordering': ['tema__nome', 'ano', 'numero'],
                'unique_together': {('tipo', 'numero', 'ano')},
            },
        ),
    ]
