# Generated by Django 4.2.7 on 2025-08-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0002_auto_20250806_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_atualizados', models.JSONField(help_text='Dados recebidos da API externa na atualização')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da atualização')),
                ('proposicao', models.ForeignKey(help_text='Proposição à qual este histórico pertence', on_delete=django.db.models.deletion.CASCADE, related_name='historicos_atualizacao', to='pauta.proposicao')),
            ],
            options={
                'verbose_name': 'Histórico de Atualização',
                'verbose_name_plural': 'Históricos de Atualização',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
