# Generated by Django 4.2.7 on 2025-08-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0003_historicoatualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='ementa',
            field=models.TextField(blank=True, help_text='Ementa da proposição', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='papel_sf',
            field=models.CharField(blank=True, help_text='Objetivo do processo no Senado Federal (ex: Revisora)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_autoria',
            field=models.CharField(blank=True, help_text='Autoria do processo (ex: Câmara dos Deputados)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_codigo_materia',
            field=models.BigIntegerField(blank=True, help_text='Código da matéria no sistema do Senado Federal', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_data_apresentacao',
            field=models.DateField(blank=True, help_text='Data de apresentação do processo no Senado Federal', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_id',
            field=models.BigIntegerField(blank=True, help_text='ID do processo no sistema do Senado Federal', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_last_info',
            field=models.CharField(blank=True, help_text='Última informação atualizada do processo (ex: EVENTO_LEGISLATIVO)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_lastupdate_date',
            field=models.DateTimeField(blank=True, help_text='Data da última atualização do processo no Senado Federal', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_tramitando',
            field=models.CharField(blank=True, help_text='Indica se o processo está tramitando (ex: Sim, Não)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='tipo_conteudo',
            field=models.CharField(blank=True, help_text='Tipo de conteúdo do processo (ex: Norma Geral)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='tipo_documento',
            field=models.CharField(blank=True, help_text='Tipo de documento do processo (ex: Projeto de Lei Ordinária)', max_length=100, null=True),
        ),
    ]
