# Generated by Django 4.2.7 on 2025-08-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0005_make_eixo_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='autor',
            field=models.CharField(blank=True, help_text='Nome do autor da proposição', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='casa_inicial',
            field=models.CharField(blank=True, choices=[('CD', 'Câmara dos Deputados'), ('SF', 'Senado Federal')], help_text='Casa onde a proposição foi iniciada', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='cd_id',
            field=models.IntegerField(blank=True, help_text='ID da proposição na API da Câmara dos Deputados', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='data_apresentacao',
            field=models.DateField(blank=True, help_text='Data de apresentação da proposição', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='erro_sincronizacao',
            field=models.TextField(blank=True, help_text='Mensagem de erro da última tentativa de sincronização', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sf_id',
            field=models.IntegerField(blank=True, help_text='ID da proposição na API do Senado Federal', null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última sincronização com as APIs', null=True),
        ),
    ]
