# Generated by Django 4.2.7 on 2025-08-13 23:21

# pauta/migrations/0007_auto_20250813_2021.py

from django.db import migrations
from django.core.management import call_command
from django.conf import settings as django_settings

def load_fixture(apps, schema_editor):
    # Skip loading fixtures during test runs
    if getattr(django_settings, 'TESTING', False):
        return
    call_command('loaddata', 'data_dump.json')

def unload_fixture(apps, schema_editor):
    # Reverse operation - typically not needed for data fixtures
    # but included for completeness
    pass


class Migration(migrations.Migration):

    dependencies = [
        # Coloque aqui a dependência da migração anterior, que normalmente
        # é a última migração de esquema. Ex: ('seu_app', '0001_initial'),
        # Certifique-se de que o esquema do banco já exista antes de carregar os dados.
        ('pauta', '0006_proposicao_autor_proposicao_casa_inicial_and_more')
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]