# Generated by Django 4.2.7 on 2025-08-13 23:21

# pauta/migrations/0007_auto_20250813_2021.py

from django.db import migrations
from django.core.management import call_command
from django.conf import settings as django_settings

def load_fixture(apps, schema_editor):
    # Skip loading fixtures during test runs
    if getattr(django_settings, 'TESTING', False):
        return
    call_command('loaddata', 'data_dump.json')

def unload_fixture(apps, schema_editor):
    # Reverse operation - typically not needed for data fixtures
    # but included for completeness
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0006_proposicao_autor_proposicao_casa_inicial_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),  # Django auth tables
        ('sessions', '0001_initial'),  # Django session table
        ('contenttypes', '0002_remove_content_type_name'),  # Content types
        ('admin', '0003_logentry_add_action_flag_choices'),  # Admin log
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]