# Generated by Django 4.2.7 on 2025-08-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0007_auto_20250813_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='casa_inicial',
            field=models.CharField(blank=True, choices=[('CD', 'Câmara dos Deputados'), ('SF', 'Senado Federal'), ('EXECUTIVO', 'Poder Executivo'), ('OUTROS', 'Outras Entidades')], help_text='Casa onde a proposição foi iniciada', max_length=10, null=True),
        ),
    ]
