# Generated by Django 4.2.7 on 2025-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0008_alter_proposicao_casa_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='current_house',
            field=models.CharField(blank=True, choices=[('CD', 'Câmara dos Deputados'), ('SF', 'Senado Federal'), ('EXECUTIVO', 'Poder Executivo'), ('OUTROS', 'Outras Entidades')], help_text='Casa onde a proposição está atualmente tramitando', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='ementa',
            field=models.TextField(blank=True, help_text='Ementa da proposição', null=True),
        ),
    ]
