# Generated by Django 4.2.7 on 2025-08-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0009_proposicao_current_house_proposicao_ementa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='autor',
            field=models.TextField(blank=True, help_text='Nome do autor da proposição', null=True),
        ),
    ]
