# Generated by Django 4.2.7 on 2025-08-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0010_change_autor_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistorySF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(help_text='ID do informe legislativo no SF')),
                ('data', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('colegiado', models.JSONField(blank=True, null=True)),
                ('ente_administrativo', models.JSONField(blank=True, null=True)),
                ('id_situacao_iniciada', models.IntegerField(blank=True, null=True)),
                ('sigla_situacao_iniciada', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_record', models.JSONField(help_text='Registro bruto do SF sem documentosAssociados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_sf', to='pauta.proposicao')),
            ],
            options={
                'verbose_name': 'Atividade SF',
                'verbose_name_plural': 'Atividades SF',
                'ordering': ['proposicao_id', 'data', 'record_id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityHistoryCD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(help_text='ID da tramitação na Câmara')),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_record', models.JSONField(help_text='Registro bruto da Câmara')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_cd', to='pauta.proposicao')),
            ],
            options={
                'verbose_name': 'Atividade CD',
                'verbose_name_plural': 'Atividades CD',
                'ordering': ['proposicao_id', 'data_hora', 'record_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityhistorysf',
            unique_together={('proposicao', 'record_id')},
        ),
        migrations.AlterUniqueTogether(
            name='activityhistorycd',
            unique_together={('proposicao', 'record_id')},
        ),
    ]
