# Generated by Django 4.2.7 on 2025-08-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0011_activityhistory_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamaraActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e hora da tramitação')),
                ('sequencia', models.IntegerField(help_text='Número sequencial da tramitação')),
                ('sigla_orgao', models.CharField(help_text='Sigla do órgão responsável', max_length=20)),
                ('uri_orgao', models.URLField(blank=True, help_text='URI do órgão na API', max_length=500, null=True)),
                ('uri_ultimo_relator', models.URLField(blank=True, help_text='URI do último relator', max_length=500, null=True)),
                ('regime', models.CharField(blank=True, help_text='Regime de tramitação', max_length=100, null=True)),
                ('descricao_tramitacao', models.CharField(help_text='Descrição do tipo de tramitação', max_length=255)),
                ('cod_tipo_tramitacao', models.CharField(help_text='Código do tipo de tramitação', max_length=10)),
                ('descricao_situacao', models.CharField(blank=True, help_text='Descrição da situação', max_length=255, null=True)),
                ('cod_situacao', models.IntegerField(blank=True, help_text='Código da situação', null=True)),
                ('despacho', models.TextField(help_text='Despacho da tramitação')),
                ('url', models.URLField(blank=True, help_text='URL para mais detalhes', max_length=500, null=True)),
                ('ambito', models.CharField(blank=True, help_text='Âmbito da tramitação', max_length=50, null=True)),
                ('apreciacao', models.CharField(blank=True, help_text='Tipo de apreciação', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
                ('proposicao', models.ForeignKey(help_text='Proposição à qual esta atividade pertence', on_delete=django.db.models.deletion.CASCADE, related_name='camara_activities', to='pauta.proposicao')),
            ],
            options={
                'verbose_name': 'Histórico de Atividade - Câmara',
                'verbose_name_plural': 'Históricos de Atividade - Câmara',
                'ordering': ['proposicao', '-data_hora', '-sequencia'],
                'unique_together': {('proposicao', 'sequencia')},
            },
        ),
        migrations.CreateModel(
            name='SenadoActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_informe', models.IntegerField(help_text='ID único do informe legislativo')),
                ('data', models.DateField(help_text='Data do informe legislativo')),
                ('descricao', models.TextField(help_text='Descrição detalhada da atividade')),
                ('colegiado_codigo', models.IntegerField(blank=True, help_text='Código do colegiado', null=True)),
                ('colegiado_casa', models.CharField(blank=True, help_text='Casa do colegiado', max_length=10, null=True)),
                ('colegiado_sigla', models.CharField(blank=True, help_text='Sigla do colegiado', max_length=20, null=True)),
                ('colegiado_nome', models.CharField(blank=True, help_text='Nome do colegiado', max_length=255, null=True)),
                ('ente_administrativo_id', models.IntegerField(blank=True, help_text='ID do ente administrativo', null=True)),
                ('ente_administrativo_casa', models.CharField(blank=True, help_text='Casa do ente administrativo', max_length=10, null=True)),
                ('ente_administrativo_sigla', models.CharField(blank=True, help_text='Sigla do ente administrativo', max_length=20, null=True)),
                ('ente_administrativo_nome', models.CharField(blank=True, help_text='Nome do ente administrativo', max_length=255, null=True)),
                ('id_situacao_iniciada', models.IntegerField(blank=True, help_text='ID da situação iniciada', null=True)),
                ('sigla_situacao_iniciada', models.CharField(blank=True, help_text='Sigla da situação iniciada', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
                ('proposicao', models.ForeignKey(help_text='Proposição à qual esta atividade pertence', on_delete=django.db.models.deletion.CASCADE, related_name='senado_activities', to='pauta.proposicao')),
            ],
            options={
                'verbose_name': 'Histórico de Atividade - Senado',
                'verbose_name_plural': 'Históricos de Atividade - Senado',
                'ordering': ['proposicao', '-data', '-id_informe'],
                'unique_together': {('proposicao', 'id_informe')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityhistorysf',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='activityhistorysf',
            name='proposicao',
        ),
        migrations.DeleteModel(
            name='ActivityHistoryCD',
        ),
        migrations.DeleteModel(
            name='ActivityHistorySF',
        ),
    ]
