# Generated by Django 4.2.7 on 2025-08-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0012_camaraactivityhistory_senadoactivityhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='selected',
            field=models.BooleanField(default=False, help_text='Indica se esta proposição foi selecionada pelo algoritmo como representativa do tema'),
        ),
    ]
