# Generated by Django 4.2.7 on 2025-08-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0012_camaraactivityhistory_senadoactivityhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senadoactivityhistory',
            options={'ordering': ['proposicao', '-data_inicio', '-id_situacao'], 'verbose_name': 'Histórico de Atividade - Senado', 'verbose_name_plural': 'Históricos de Atividade - Senado'},
        ),
        migrations.AlterUniqueTogether(
            name='senadoactivityhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='senadoactivityhistory',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Data de fim da situação (null se ainda ativa)', null=True),
        ),
        migrations.AddField(
            model_name='senadoactivityhistory',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data de início da situação', null=True),
        ),
        migrations.AddField(
            model_name='senadoactivityhistory',
            name='id_situacao',
            field=models.IntegerField(blank=True, help_text='ID único da situação (idTipo da API)', null=True),
        ),
        migrations.AddField(
            model_name='senadoactivityhistory',
            name='sigla_situacao',
            field=models.CharField(blank=True, help_text='Sigla da situação', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='senadoactivityhistory',
            name='descricao',
            field=models.TextField(help_text='Descrição detalhada da situação'),
        ),
        migrations.AlterUniqueTogether(
            name='senadoactivityhistory',
            unique_together={('proposicao', 'id_situacao')},
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='data',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='id_informe',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='id_situacao_iniciada',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='sigla_situacao_iniciada',
        ),
    ]
