# Generated by Django 4.2.7 on 2025-08-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0013_update_senado_activity_history_for_situacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='colegiado_casa',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='colegiado_nome',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='colegiado_sigla',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='ente_administrativo_casa',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='ente_administrativo_id',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='ente_administrativo_nome',
        ),
        migrations.RemoveField(
            model_name='senadoactivityhistory',
            name='ente_administrativo_sigla',
        ),
    ]
