# Generated by Django 4.2.7 on 2025-08-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0014_increase_activity_field_lengths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposicao',
            old_name='casa_inicial',
            new_name='iniciadora',
        ),
        migrations.AddField(
            model_name='proposicao',
            name='revisora',
            field=models.CharField(blank=True, choices=[('CD', 'Câmara dos Deputados'), ('SF', 'Senado Federal'), ('EXECUTIVO', 'Poder Executivo'), ('OUTROS', 'Outras Entidades')], help_text='Casa que revisará a proposição', max_length=10, null=True),
        ),
    ]
